name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - pnpm-lock.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Configure PNPM
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Use Node.js v22.11.0
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22.11.0'
          cache: pnpm

      - name: Install packages
        run: pnpm i

      - name: Lint application
        run: pnpm lint
